services:
  - type: web
    name: ecommerce-springboot
    env: docker
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/E-Commerce_Shopping_Cart-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DB_URL
        value: mysql://root:YzCglGQZuGcUQiAGqzyvFHDJhYscMLqr@mysql.railway.internal:3306/railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: YzCglGQZuGcUQiAGqzyvFHDJhYscMLqr
